version: '3'

services:
  web:
    build: .
    command: >
      sh -c "python create_superuser.py &&
             gunicorn --bind 0.0.0.0:8000 wallet_project.wsgi:application"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: wallet_project.settings
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  redis:
    image: "redis:latest"
