# Generated by Django 3.2 on 2023-12-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0002_auto_20231212_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
