# Generated by Django 3.2 on 2023-12-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0005_alter_transaction_target_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
